Added "Senior Product Developer - Data Farming" JD
oceanprotocol/jobs pull request #2
Opened 2021-09-03 09:34 UTC by AnaLoznianu

Changes proposed in this PR:

- Added "Senior Product Developer - Data Farming" JD
- Added link readme to the new DF JD

2021-09-03 09:53 UTC, DraganaRajacic approved these changes

2021-09-03 10:03 UTC, DraganaRajacic approved these changes

2021-09-03 10:03 UTC, DraganaRajacic commented on df.md
> +* +3 years of experience working in technical/development roles in the crypto projects
3+ years of experience

2021-09-03 10:03 UTC, DraganaRajacic commented on df.md
> +* +2 years Hands-on experience in development in Web3 and Web2 tech stack
2+ years Hands-on experience

2021-09-03 10:23 UTC, kremalicious commented
Developer vs. Engineer. If we mean engineer here then please use engineer.

2021-09-03 11:08 UTC, DraganaRajacic commented
The role is to evolve and optimize the program based on users engagement and community feedback. That means to measure KPI's and fine tune of rewarding function according to the users activities. That is why was Product Developer, not Engineer

2021-09-03 11:55 UTC, kremalicious commented
So it's a Senior Program Manager or Technical Program Manager you are looking for? "Product" implies they are supposed to build a product, but data farming is no product but a program to increase usage of our actual product. Are they supposed to actively work on Ocean Market? If not, they have nothing to do with product.

As for "developer" you already see that this term is too vague and ambiguous as it can be understood as coding or not depending on who you ask. And the people you want to reach with this here might look for other things than "developer"

2021-09-04 08:13 UTC, trentmc commented
Even if a product's main goal is to help drive adoption of another product, it can still be a product on its own. 

Data Farming has the trappings of a product: software artifacts & related processes, clear targets, a team to drive it, a life cycle (vs a project with a date that ends), iterations to keep improving it, etc. By framing as a product then we get all the tools and mental models of products. So we are going to continue calling it a product.

However none of our other job titles around software development roles have "product" in them. They don't need to. It adds confusion, as Matthias has pointed out. Therefore I recommend that we do _not_ have "product" in this job description either. "Senior Developer - Data Farming" and that's it.

2021-09-04 08:39 UTC, trentmc requested changes

2021-09-04 08:39 UTC, trentmc commented on df.md
> +* 2+ years Hands-on experience in development in Web3 and Web2 tech stack
My comments are for the two bullets above: 3+ years exp crypto, 2+ years dev Web 2 & Web3

Problems:
- 3+ years working in Web3 is a big ask; it greatly narrows our candidates. Same for "2+ years working in Web3 development". It's unnecessarily constraining.
- Web2 experience is a radically different thing than Web3, it should be its own line.
- Web2 and Web3 it should be more specific on which stack. 
- Having two separate lines on Web3 is a bit confusing. If you ask for a min req on Solidity experience you don't need a separate line on more general "technical" Web3 experience

Suggested new lines:

- 6+ months Solidity experience
- 3+ years full-stack Web2 experience including NodeJS

2021-09-04 08:39 UTC, trentmc commented on df.md
> +* Stellar research skills
There are too many bullets for "minimum qualifications", and too few in "Nice to haves". You'll scare off candidates.

Suggestion: move some "minimum qualifications" into "nice to haves".

2021-09-04 08:39 UTC, trentmc commented on df.md
> +* Over time they will ideally automate/delegate parts or sections of the program for optimization. Some things can be automated using script and tech. They will design initiatives to decentralize oth
The list of responsibilities is too long. Yet still weirdly vague.

Here's a new set, inspired by https://github.com/oceanprotocol/jobs/blob/main/sr-dev.md:
- You will design & build software for Ocean Protocol Data Farming, including scripts for reading on-chain data, performing analysis, token distribution, and whatever else is needed for the Data Farming process. The scope of the software will grow over time, based on feedback from the community, e.g. to do on-chain voting and interact with more protocols.
- You will co-plan and co-design the product with the Data Farming team in an agile, open-source development process

2021-09-04 08:39 UTC, trentmc commented on df.md
> +Ocean has a vibrant, expanding ecosystem of data suppliers, data consumers, stakers, and community developers. To serve it better, we’re hiring! If you are someone that loves to build things and care
We can make the above more specific.

How about:

Data Farming is a specific initiative in the spirit of liquidity mining, with generous OCEAN rewards to ecosystem participants who drive the supply of data. We're growing the Data Farming team. If you love to work with crypto, to build and to engage deeply with an enthusiastic community, we want to hear from you.

2021-09-04 08:39 UTC, trentmc commented on df.md
> +* Creative, with extensive writing/public speaking experience
Everyone will say they're "creative". We don't need this hear.

And we don't need extensive public speaking experience for this role.

I recommend to (a) remove this line, and (b) in "Nice to haves" add "You’re an excellent writer."

2021-09-04 08:39 UTC, trentmc commented on df.md
> +* Strong skills in project management and project ownership
I don't understand the three lines above. The role is for a software developer. Yet here it's around running / leading a project. Not appropriate here, and a very different skillset than sw dev. 

Recommend deleting the lines.

2021-09-04 08:39 UTC, trentmc commented on df.md
> +* Previous experience in working on Open source projects
This list is missing out on the nice list of "nice to haves" from jobs/sr-dev.md. I recommend bringing those back, they are relevant and will get applicants excited about the position.

I've copied them here, and tuned a bit for DF. The latter point is especially important to keep, without it people might inadvertently forget these are "nice to haves" (it's a psychology thing)

- 2+ years Python 
- 1+ years CI/CD experience (e.g. Travis, tox)
- You’re obsessed with blockchain. You yield farm in your spare time and engage in crypto Twitter
- You’re an excellent writer.
- Preferred work hours: 9-5ish on European time zones
- We don’t expect you to be an expert in all of these. Rather, we’d love to see that you’re interested in them, perhaps know one or two as a starting point, and most importantly, that you’ll learn more about them as you grow with us professionally and personally.

2021-09-04 08:40 UTC, trentmc commented on README.md
> +- 🦈 [Senior Product Developer - Data Farming](/df.md)
"Product" isn't needed. And "Blockchain" helps attract actual blockchain developers, especially due to keyword searches.

Therefore I recommend changing the line to:
"Senior Blockchain Developer - Data Farming"

2021-09-13 13:42 UTC, trentmc approved these changes

2021-09-20 10:00 UTC, merged