Added DAO Engineer DJ
oceanprotocol/jobs pull request #4
Opened 2021-09-22 15:58 UTC by idiom-bytes

Opening up PR for DAO Engineer DJ

2021-09-23 11:17 UTC, AnaLoznianu requested changes

2021-09-23 11:17 UTC, AnaLoznianu commented on dao.md
> +[OceanDAO](https://www.oceanprotocol.com/dao) is a key component that brings decentralization and scale to participants that are driving traction into the Ocean ecosystem. We’re growing the OceanDAO
If you love to work with crypto, to build and **_to_** engage.... remove the 'to' in front of engage

2021-09-23 11:17 UTC, AnaLoznianu commented on dao.md
> +* 3+ years backend experience, including NodeJS
I would order the experience needed based on years, in reverse order. To 4+ years of software experience to be the first one, then 3+ years of backend the second one and the 6+ months, the last one

2021-09-23 11:17 UTC, AnaLoznianu commented on dao.md
> +* Proven experience in building meaningful technical communities around projects and ability to build and manage relationship with a key stakeholders
* Manage relationships(plural)
* With key stakeholders, remove the 'a' key stakeholders

2021-09-23 11:17 UTC, AnaLoznianu commented on dao.md
> +* Excellent writing and communication skills. Candidate will engage with the community, receive feedback, identify usage patterns, and communicate macro outcomes.
Instead of 'Candidate', I would make this personal. You will engage with the community...

2021-09-23 14:25 UTC, idiom-bytes commented
Ok, I've updated the description based on your recommendations. Thank you!

@trentmc I have adjusted the technical expectations to focus more on web3/backend/infra. This reflects the intention on separating backend/frontend initiatives, in addition to decentralizing more frontend stuff (i.e. Uni Labs vs. Uni FE debacle). Moreover, Ocean whitepaper and looking out further into the future (beyond 2022) may bring more onchain systems, and perhaps even para-chain implementations of voting/funding/etc... that make these systems low-cost & truly decentralized (vs. off-chain gasless voting on proposals via snapshot.... which is same same but different). 

Please LMK if this checks out with your intuitions.

2021-09-23 19:53 UTC, trentmc approved these changes

2021-09-23 19:53 UTC, trentmc commented on dao.md
> +* 6+ months of Solidity experience
Also 1+ years web3.js

2021-09-23 19:53 UTC, trentmc commented on dao.md
> +* your CV
Also ask for eth address(es) or ens names. Call it optional. This will be super useful for us though!

2021-09-23 19:53 UTC, trentmc commented
Overall I'm fine with it.

2021-09-27 09:48 UTC, AnaLoznianu approved these changes

2021-09-27 16:29 UTC, merged